### ISSUE TITLE
絞り込み検索でカテゴリー名でも検索するように改修

### ISSUE THREAD

**Issue by northprint** [aigidjp/simple-geo-viewer#36]

**Comment by Kanahiro** [comment]
以下の仕様とします

カテゴリー名がマッチした場合 -> カテゴリ以下のDataは全て表示する
カテゴリー名がマッチしていないがData.titleがマッチした場合 -> 親カテゴリおよびマッチしたDataのみ表示する

**Comment by northprint** [comment]
ありがとうございます！その仕様で問題ないです
