### ISSUE TITLE
レイヤー単位のダウンロード対応

### ISSUE THREAD

**Issue by northprint** [aigidjp/simple-geo-viewer#5]

**Comment by northprint** [comment]
5/27目標

**Comment by Kanahiro** [comment]
これは、`./src/assets/config.json`のレイヤー定義で言う、`source`のファイルをダウンロードさせる機能、でOKですか？

**Comment by Kanahiro** [comment]
<s>その場合、`source`に入るのはダウンロード可能なファイル（JSONファイルなど）だけ、ということで実装してOKですか？</s>

**Comment by Kanahiro** [comment]
さみだれですみません、`README.md`によれば、ラスタータイルのURLなども入りうるようですね。
それで言うとダウンロードさせる意味がありそうなのは、`geojson`, `gltf`, `icon`です。
これらだけに、ダウンロードボタンが表示される、という仕様でOKですか？

**Comment by northprint** [comment]
今の実装だと、カテゴリートップにダウンロードボタンが付いていますが
デジタルシティではレイヤー毎にダウンロードボタンが必要なので、その対応になります
https://www.digitalsmartcity.jp/susono-city/demo/
そのダウンロードボタンの動きなのですが、ファイルのダウンロードだけではなく、外部リンクも入っているので、Aタグの機能として実装する必要があります

で、「現状のカテゴリートップのダウンロードボタン機能は活かしつつ、設定がなければ非表示にする」
という実装が必要です

**Comment by northprint** [comment]
参考
現状の実装を利用しているページ
https://view.city-cps.net/

**Comment by Kanahiro** [comment]
なるほど了解です、理解しました。
加えて、カテゴリートップの方のダウンロードボタンは消す、という仕様で理解しました。

**Comment by northprint** [comment]
すみません、カテゴリートップの方のダウンロードボタンは消すのではなく
「現状のカテゴリートップのダウンロードボタン機能は活かしつつ、jsonに設定がなければ非表示にする」
という仕様でとお願いされておりまして
両方表示させることが可能という仕様になります
