### ISSUE TITLE
人流のトラッキングデータ表示対応

### ISSUE THREAD

**Issue by northprint** [aigidjp/simple-geo-viewer#6]

**Comment by northprint** [comment]
GeoJSON_TimeSeriesPolygon
メッシュベース疑似人流データ(東大)
https://data.digitalsmartcity.jp/susono/persontrip/boundaryvolume.geojson
3Dメッシュベース疑似人流データ(東大)
https://data.digitalsmartcity.jp/susono/persontrip/boundaryvolume.geojson

GeoJSON_TimeSeriesLine
リンクベース疑似人流データ(東大)
https://data.digitalsmartcity.jp/susono/persontrip/linkvolume.geojson

Trips
平日の人の流れ（2016年・東駿河湾都市圏調査より作成）出典: 東京大学CSIS
https://data.digitalsmartcity.jp/person_flow/trips_weekday_susono_v8.json
休日の人の流れ（2016年・東駿河湾都市圏より作成）出典: 東京大学CSIS
https://data.digitalsmartcity.jp/person_flow/trips_holiday_susono_v8.json

**Comment by Kanahiro** [comment]
TimeSeriesPolygonは実装が終わりました
つづいてラインの方やろうと思うのですが
> GeoJSON_TimeSeriesLine
リンクベース疑似人流データ(東大)
https://data.digitalsmartcity.jp/susono/persontrip/linkvolume.geojson

こちら、JSONファイルが84.9MBあるのですが、問題ないですか？


しらべると、やっぱりデジタル裾野ではこれを読み込んでるみたいなので、これで進めます。
gzipかなにかで圧縮されて、通信量はそれほど大きくないのかもしれません。。。

**Comment by northprint** [comment]
すみません、よろしくお願いします🙇‍♂️
