### ISSUE TITLE
AEDのアイコンレイヤーが表示されない

### ISSUE THREAD

**Issue by DevKoukiMaeda** [aigidjp/simple-geo-viewer#60]

**Comment by DevKoukiMaeda** [comment]
- aed.jsonのリクエストのステータスコードは 200
- 別の表示できるレイヤーとjsonを入れ替えるとレイヤーが表示される
- 別の表示できるレイヤーにaed.jsonを入れ替えるとレイヤーが表示されない
以上のことからAEDのgeojsonのフォーマットの問題であると考えられます。

**Comment by northprint** [comment]
なるほど。。
元サイトはMapboxLayerだから表示できている感じな気がしますね、、、
これはデータの方を変更できるか微妙なので、問題の認識と解決方法の調査をしたいと思います

**Comment by Kanahiro** [comment]
https://data.digitalsmartcity.jp/susono/facility/aed.json

あきらかにGeoJSONのフォーマットではないですね。GeoJSON-Featureの配列になっています。
上記のJSONをJavaScriptで読み込んだ変数を`aedJson`として

```typescript
const geojson = {
    type: 'FeatureCollection',
    features: aedJson
}
```

とすれば読めると思われます。

**Comment by northprint** [comment]
調査ありがとうございます！
@DevKoukiMaeda 
- typeの変更
- 当該typeの場合の処理を追加
の実装は可能でしょうか？

**Comment by DevKoukiMaeda** [comment]
@northprint 
本日中ですか？
現在作成中です

**Comment by northprint** [comment]
@DevKoukiMaeda 
可能であれば本日中でおねがいしたく
よろしくお願いします
